# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

pool:
  vmImage: ubuntu-latest
    
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_frontend
  displayName: Build image
  jobs:
  - job: BuildFrontend
    displayName: BuildFrontend
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'Frontend/Dockerfile'
        tags: |
          $(tag)
  - job: BuildBackend
    displayName: BuildBackend
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'Backend/TodoList.Api/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: gr8riaz/cpsretest01
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        repository: contosoRepository  gr8riaz/Gh4z4l4Ri4z$$  
        tags: |
          $(tag)

